"""add img_url to announcement

Revision ID: 3304ccebeb33
Revises: e8a7b28dfb4a
Create Date: 2024-07-30 18:38:11.912221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3304ccebeb33'
down_revision = 'e8a7b28dfb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
