"""Initial migration.

Revision ID: 3927d4a27913
Revises: edda0812ff35
Create Date: 2024-08-26 18:16:51.535985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3927d4a27913'
down_revision = 'edda0812ff35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_days', sa.String(length=25), nullable=False))
        batch_op.drop_column('suggested_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_day', sa.VARCHAR(length=25), nullable=False))
        batch_op.drop_column('suggested_days')

    # ### end Alembic commands ###
