"""Initial migration.

Revision ID: 4109e1861a33
Revises: 7d09f1b23a4a
Create Date: 2024-08-20 16:29:34.923139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4109e1861a33'
down_revision = '7d09f1b23a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=80), nullable=False))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
