"""Initial migration.

Revision ID: edda0812ff35
Revises: 4109e1861a33
Create Date: 2024-08-26 16:22:25.234877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edda0812ff35'
down_revision = '4109e1861a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_day', sa.String(length=25), nullable=False))

    with op.batch_alter_table('transaction_step', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_step', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('class_request', schema=None) as batch_op:
        batch_op.drop_column('suggested_day')

    # ### end Alembic commands ###
